# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aislab\Desktop\工具機計畫project\工具機可視化介面\sidebar1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 991)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.change_btn = QtWidgets.QPushButton(self.widget)
        self.change_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.change_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/menu-4-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_btn.setIcon(icon)
        self.change_btn.setIconSize(QtCore.QSize(20, 20))
        self.change_btn.setCheckable(True)
        self.change_btn.setObjectName("change_btn")
        self.horizontalLayout_4.addWidget(self.change_btn)
        spacerItem = QtWidgets.QSpacerItem(305, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_input = QtWidgets.QLineEdit(self.widget)
        self.search_input.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.search_input.setFont(font)
        self.search_input.setStyleSheet("QLineEdit{\n"
"        border: none;\n"
"        padding: 5px 10px;}\n"
"QLineEdit:focus {\n"
"        background-color: #70B9FE;\n"
"    }")
        self.search_input.setObjectName("search_input")
        self.horizontalLayout.addWidget(self.search_input)
        self.search_btn = QtWidgets.QPushButton(self.widget)
        self.search_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.search_btn.setStyleSheet("QPushButton{\n"
"border: none;}")
        self.search_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/search-13-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon1)
        self.search_btn.setIconSize(QtCore.QSize(20, 20))
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 250))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_4 = QtWidgets.QWidget(self.groupBox)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5.addWidget(self.widget_4)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 250))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_6 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_7.addWidget(self.widget_6)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 250))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_6.addWidget(self.widget_5)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 250))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_9 = QtWidgets.QWidget(self.groupBox_4)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_8.addWidget(self.widget_9)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 3, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_7 = QtWidgets.QWidget(self.groupBox_6)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_10.addWidget(self.widget_7)
        self.gridLayout_2.addWidget(self.groupBox_6, 1, 2, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_9.addWidget(self.widget_2)
        self.gridLayout_2.addWidget(self.groupBox_5, 1, 0, 1, 2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_8 = QtWidgets.QWidget(self.groupBox_7)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_11.addWidget(self.widget_8)
        self.gridLayout_2.addWidget(self.groupBox_7, 2, 0, 1, 4)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_11 = QtWidgets.QGroupBox(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    border-radius: 10px;  /* 圓角邊框 */\n"
"    border: 2px solid #b0b0b0;  /* 淺灰色邊框 */\n"
"    background-color: #f0f0f0;  /* 淺灰色背景 */\n"
"    padding: 8px;  /* 內邊距 */\n"
"    color: #333;  /* 文字顏色 */\n"
"}\n"
"\n"
"QTextEdit:hover {\n"
"    border: 2px solid #8f8f8f;  /* 滑過時邊框變深灰 */\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 2px solid #6d6d6d;  /* 獲得焦點時邊框變成深灰色 */\n"
"    background-color: #ffffff;  /* 焦點時背景變白 */\n"
"}\n"
"\n"
"QTextEdit:disabled {\n"
"    background-color: #d0d0d0;  /* 禁用時背景變灰 */\n"
"    color: #a0a0a0;  /* 禁用時文字顏色變灰 */\n"
"}\n"
"")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_14.addWidget(self.textEdit)
        self.gridLayout_4.addWidget(self.groupBox_11, 0, 0, 2, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mic_start = QtWidgets.QPushButton(self.groupBox_12)
        self.mic_start.setMinimumSize(QtCore.QSize(350, 350))
        self.mic_start.setMaximumSize(QtCore.QSize(350, 350))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        self.mic_start.setFont(font)
        self.mic_start.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 170, 255);\n"
"color:black;\n"
"border-radius:175px;\n"
"border:2px groove gray;\n"
"border-style: solid;\n"
"}\n"
"QPushButton:pressed{\n"
"color: #fff;\n"
"border: 5px solid #ecd182;\n"
"}")
        self.mic_start.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/sound.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mic_start.setIcon(icon2)
        self.mic_start.setIconSize(QtCore.QSize(200, 200))
        self.mic_start.setObjectName("mic_start")
        self.verticalLayout_6.addWidget(self.mic_start)
        self.mic_cancel = QtWidgets.QPushButton(self.groupBox_12)
        self.mic_cancel.setMinimumSize(QtCore.QSize(350, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.mic_cancel.setFont(font)
        self.mic_cancel.setObjectName("mic_cancel")
        self.verticalLayout_6.addWidget(self.mic_cancel)
        self.input_text = QtWidgets.QPushButton(self.groupBox_12)
        self.input_text.setMinimumSize(QtCore.QSize(350, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.input_text.setFont(font)
        self.input_text.setStyleSheet("QPushButton {\n"
"    border: 2px solid black;  /* 設置黑色邊框，2px寬度 */\n"
"    border-radius: 5px;      /* 圓角邊框（可選） */\n"
"    padding: 5px;            /* 按鈕內部邊距，讓文字不緊貼邊框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: darkblue;  /* 鼠標懸停時改變邊框顏色 */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/send.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_text.setIcon(icon3)
        self.input_text.setIconSize(QtCore.QSize(30, 30))
        self.input_text.setObjectName("input_text")
        self.verticalLayout_6.addWidget(self.input_text)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.speech_start = QtWidgets.QPushButton(self.groupBox_12)
        self.speech_start.setMinimumSize(QtCore.QSize(350, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.speech_start.setFont(font)
        self.speech_start.setObjectName("speech_start")
        self.verticalLayout_6.addWidget(self.speech_start)
        self.quit = QtWidgets.QPushButton(self.groupBox_12)
        self.quit.setMinimumSize(QtCore.QSize(350, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.quit.setFont(font)
        self.quit.setObjectName("quit")
        self.verticalLayout_6.addWidget(self.quit)
        self.gridLayout_4.addWidget(self.groupBox_12, 0, 1, 2, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_17 = QtWidgets.QWidget(self.page_4)
        self.widget_17.setMinimumSize(QtCore.QSize(800, 800))
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_19 = QtWidgets.QWidget(self.widget_17)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.widget_19)
        self.label_6.setMinimumSize(QtCore.QSize(50, 100))
        self.label_6.setMaximumSize(QtCore.QSize(100, 100))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icon/icon/robot.ico"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_15.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.widget_19)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_15.addWidget(self.label_9)
        self.widget_21 = QtWidgets.QWidget(self.widget_19)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.start_chat_button = QtWidgets.QPushButton(self.widget_21)
        self.start_chat_button.setMinimumSize(QtCore.QSize(30, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.start_chat_button.setFont(font)
        self.start_chat_button.setObjectName("start_chat_button")
        self.horizontalLayout_17.addWidget(self.start_chat_button)
        self.stop_chat_button = QtWidgets.QPushButton(self.widget_21)
        self.stop_chat_button.setMinimumSize(QtCore.QSize(30, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.stop_chat_button.setFont(font)
        self.stop_chat_button.setObjectName("stop_chat_button")
        self.horizontalLayout_17.addWidget(self.stop_chat_button)
        self.horizontalLayout_15.addWidget(self.widget_21)
        self.verticalLayout_8.addWidget(self.widget_19)
        self.widget_20 = QtWidgets.QWidget(self.widget_17)
        self.widget_20.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.display_chat_textEdit = QtWidgets.QTextEdit(self.widget_20)
        self.display_chat_textEdit.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.display_chat_textEdit.setFont(font)
        self.display_chat_textEdit.setStyleSheet("QTextEdit {\n"
"    border-radius: 10px;  /* 圓角邊框 */\n"
"    border: 2px solid #b0b0b0;  /* 淺灰色邊框 */\n"
"    background-color: #f0f0f0;  /* 淺灰色背景 */\n"
"    padding: 8px;  /* 內邊距 */\n"
"    color: #333;  /* 文字顏色 */\n"
"}\n"
"\n"
"QTextEdit:hover {\n"
"    border: 2px solid #8f8f8f;  /* 滑過時邊框變深灰 */\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 2px solid #6d6d6d;  /* 獲得焦點時邊框變成深灰色 */\n"
"    background-color: #ffffff;  /* 焦點時背景變白 */\n"
"}\n"
"\n"
"QTextEdit:disabled {\n"
"    background-color: #d0d0d0;  /* 禁用時背景變灰 */\n"
"    color: #a0a0a0;  /* 禁用時文字顏色變灰 */\n"
"}\n"
"")
        self.display_chat_textEdit.setReadOnly(True)
        self.display_chat_textEdit.setObjectName("display_chat_textEdit")
        self.verticalLayout_9.addWidget(self.display_chat_textEdit)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.messages_lineedit = QtWidgets.QLineEdit(self.widget_20)
        self.messages_lineedit.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.messages_lineedit.setFont(font)
        self.messages_lineedit.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    border: 2px solid #5c9ded; /* 默認藍色邊框 */\n"
"    padding: 5px; /* 內邊距 */\n"
"    background-color: #f7f7f7; /* 淺灰色背景 */\n"
"    color: #333; /* 字體顏色 */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid #3b7fd4; /* 當滑過時邊框變成更深的藍色 */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #1e90ff; /* 當獲得焦點時，變成更鮮亮的藍色 */\n"
"    background-color: #ffffff; /* 焦點時背景變白 */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #e0e0e0; /* 禁用時背景變灰 */\n"
"    color: #a0a0a0; /* 禁用時字體顏色變灰 */\n"
"}\n"
"")
        self.messages_lineedit.setObjectName("messages_lineedit")
        self.horizontalLayout_16.addWidget(self.messages_lineedit)
        self.send_messages_button = QtWidgets.QPushButton(self.widget_20)
        self.send_messages_button.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.send_messages_button.setFont(font)
        self.send_messages_button.setStyleSheet("QPushButton {\n"
"    background-color: transparent;  /* 預設背景透明 */\n"
"    border: none;  /* 移除邊框 */\n"
"    color: #333;  /* 字體顏色 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(200, 200, 200, 0.2);  /* 滑過時顯示淺灰色背景，提升交互感 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100, 100, 100, 0.3);  /* 按下時背景變暗 */\n"
"    color: #000;  /* 按下時字體變成黑色 */\n"
"}\n"
"")
        self.send_messages_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/send1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_messages_button.setIcon(icon4)
        self.send_messages_button.setIconSize(QtCore.QSize(80, 80))
        self.send_messages_button.setObjectName("send_messages_button")
        self.horizontalLayout_16.addWidget(self.send_messages_button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.verticalLayout_8.addWidget(self.widget_20)
        self.verticalLayout_7.addWidget(self.widget_17)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setStyleSheet("QWidget\n"
" {\n"
"        background-color: #313a46;\n"
"        width:50px;\n"
"    }\n"
"QPushButton, QLabel {\n"
"        height:50px;\n"
"        border:none;\n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.icon_only_widget)
        self.label.setMinimumSize(QtCore.QSize(60, 60))
        self.label.setMaximumSize(QtCore.QSize(60, 60))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/icon/machine_logo.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dashboard_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.dashboard_btn_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/dashboard-5-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/dashboard-5-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.dashboard_btn_1.setIcon(icon5)
        self.dashboard_btn_1.setIconSize(QtCore.QSize(30, 30))
        self.dashboard_btn_1.setCheckable(True)
        self.dashboard_btn_1.setAutoExclusive(True)
        self.dashboard_btn_1.setObjectName("dashboard_btn_1")
        self.verticalLayout.addWidget(self.dashboard_btn_1)
        self.orders_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.orders_btn_1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/activity-feed-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/activity-feed-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.orders_btn_1.setIcon(icon6)
        self.orders_btn_1.setIconSize(QtCore.QSize(30, 30))
        self.orders_btn_1.setCheckable(True)
        self.orders_btn_1.setAutoExclusive(True)
        self.orders_btn_1.setObjectName("orders_btn_1")
        self.verticalLayout.addWidget(self.orders_btn_1)
        self.chat_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.chat_btn_1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/product-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/product-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.chat_btn_1.setIcon(icon7)
        self.chat_btn_1.setIconSize(QtCore.QSize(30, 30))
        self.chat_btn_1.setCheckable(True)
        self.chat_btn_1.setAutoExclusive(True)
        self.chat_btn_1.setObjectName("chat_btn_1")
        self.verticalLayout.addWidget(self.chat_btn_1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 389, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.exit_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.exit_btn_1.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icon/close-window-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn_1.setIcon(icon8)
        self.exit_btn_1.setIconSize(QtCore.QSize(30, 30))
        self.exit_btn_1.setObjectName("exit_btn_1")
        self.verticalLayout_3.addWidget(self.exit_btn_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setStyleSheet("QWidget{\n"
"background-color: #313a46;}\n"
"QPushButton {\n"
"        border:none;\n"
"        border-radius: 3px;\n"
"        text-align: left;\n"
"        padding: 8px 0 8px 15px;\n"
"        color: #788596;\n"
"    }\n"
"QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"QPushButton:checked {\n"
"        color: #fff;\n"
"    }")
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.full_menu_widget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icon/icon/machine_logo.ico"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"padding-right: 10px;\n"
"        color: #fff;}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dashboard_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.dashboard_btn_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.dashboard_btn_2.setFont(font)
        self.dashboard_btn_2.setIcon(icon5)
        self.dashboard_btn_2.setIconSize(QtCore.QSize(25, 25))
        self.dashboard_btn_2.setCheckable(True)
        self.dashboard_btn_2.setAutoExclusive(True)
        self.dashboard_btn_2.setObjectName("dashboard_btn_2")
        self.verticalLayout_2.addWidget(self.dashboard_btn_2)
        self.orders_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.orders_btn_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.orders_btn_2.setFont(font)
        self.orders_btn_2.setIcon(icon6)
        self.orders_btn_2.setIconSize(QtCore.QSize(25, 25))
        self.orders_btn_2.setCheckable(True)
        self.orders_btn_2.setAutoExclusive(True)
        self.orders_btn_2.setObjectName("orders_btn_2")
        self.verticalLayout_2.addWidget(self.orders_btn_2)
        self.chat_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.chat_btn_2.setFont(font)
        self.chat_btn_2.setIcon(icon7)
        self.chat_btn_2.setIconSize(QtCore.QSize(25, 25))
        self.chat_btn_2.setCheckable(True)
        self.chat_btn_2.setAutoExclusive(True)
        self.chat_btn_2.setObjectName("chat_btn_2")
        self.verticalLayout_2.addWidget(self.chat_btn_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 399, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.exit_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.exit_btn_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.exit_btn_2.setFont(font)
        self.exit_btn_2.setIcon(icon8)
        self.exit_btn_2.setIconSize(QtCore.QSize(25, 25))
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.verticalLayout_4.addWidget(self.exit_btn_2)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.change_btn.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.change_btn.toggled['bool'].connect(self.full_menu_widget.setHidden) # type: ignore
        self.dashboard_btn_1.toggled['bool'].connect(self.dashboard_btn_2.setChecked) # type: ignore
        self.orders_btn_1.toggled['bool'].connect(self.orders_btn_2.setChecked) # type: ignore
        self.dashboard_btn_2.toggled['bool'].connect(self.dashboard_btn_1.setChecked) # type: ignore
        self.orders_btn_2.toggled['bool'].connect(self.orders_btn_1.setChecked) # type: ignore
        self.exit_btn_2.clicked.connect(MainWindow.close) # type: ignore
        self.exit_btn_1.clicked.connect(MainWindow.close) # type: ignore
        self.chat_btn_1.toggled['bool'].connect(self.chat_btn_2.setChecked) # type: ignore
        self.chat_btn_2.toggled['bool'].connect(self.chat_btn_1.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.groupBox.setTitle(_translate("MainWindow", "Temperature"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Carbon Emissions"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Humidity"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Cutter Wear"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Humidity Variation"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Temperature Variation"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Sensor Signal"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Dialog Box"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Speech and Input Text Function"))
        self.mic_cancel.setText(_translate("MainWindow", "Cancel Speech"))
        self.input_text.setText(_translate("MainWindow", "Input Text"))
        self.speech_start.setText(_translate("MainWindow", "Start "))
        self.quit.setText(_translate("MainWindow", "Quit "))
        self.label_9.setText(_translate("MainWindow", "Machine Tool ChatRobot (Not Human, Just Robot)"))
        self.start_chat_button.setText(_translate("MainWindow", "Start "))
        self.stop_chat_button.setText(_translate("MainWindow", "Stop "))
        self.messages_lineedit.setPlaceholderText(_translate("MainWindow", "Send Messages..."))
        self.label_3.setText(_translate("MainWindow", "Dashboard"))
        self.dashboard_btn_2.setText(_translate("MainWindow", "Manage"))
        self.orders_btn_2.setText(_translate("MainWindow", "Voice"))
        self.chat_btn_2.setText(_translate("MainWindow", "Chat"))
        self.exit_btn_2.setText(_translate("MainWindow", "Exit"))
import resource_rc
